# Generated by Django 3.2.9 on 2021-12-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('grades', models.CharField(max_length=200)),
                ('average_grade', models.FloatField(max_length=200)),
            ],
        ),
    ]
